name: pylint

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*
  pull_request:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*

jobs:
  build:
    name: onPushPylint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get changed files
      id: changed-pythons
      uses: tj-actions/changed-files@v35
      with:
        files: |
          **/*.py

    - name: Install dependencies
      if: steps.changed-pythons.outputs.any_changed == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip freeze        
    
    - name: Analysing the code with pylint
      if: steps.changed-pythons.outputs.any_changed == 'true'
      run: |
        pylint ${{ steps.changed-pythons.outputs.all_changed_files }}
